language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
env:
  - pyramid_version=1.7.4
  - pyramid_version=1.8.1
  - pyramid_version=1.9
install:
  - pip install pyramid==$pyramid_version
  - python setup.py develop
script: python setup.py test
sudo: false
